C={}
C.base_value = 10000
C.all_industries = ["agriculture", "hardware", "health", "buzzwords"]
C.living_cost = 5* C.base_value
C.all_skills = ["marketing","technical","finance"]
C.starting_match_bias = 1
C.possible_starting_deficit = 7
C.development_factor = .2
C.burn_basis = 20000
C.cash_basis = 100000
window.C = C